[package]
name = "chunkwm"
version = "0.4.6"
authors = ["Splinter Suidman"]

[dependencies]
core-graphics = "0.12.4"
core-foundation = "0.4.6"

[features]
accessibility = []
border = []

[build-dependencies]
cc = "1.0"
